#RuleBook Travis CI config for maven deploy
language: java
env:
  global:
    #OSSRH_USERNAME
    - secure: "QtZ0h7bfVQ7Juw3SdaXk77AT5bQUlI3YhBZnOAOhjK6IVlPcYGMUY0J+CK2ogSoCkjoGFK+2PcBYvBalscQ0U3atY/MGvbmLA/uj8OjiFHoW2pdTWPIaiLOucOr6t2QVZoC4eSghpyTUVtdbVLt4h+rN3YRyVqxBC/wdN17lq+xgf2vRMk/4+DQxQrEu8UyvwJB1fPNJcU2goZRPwvxFp+PXQsTGfMWdNpl121lZrUnSk0ua+ZR4mFzWaNNFaQz7rSPhH/kpjhjRfTnH+vf9wYUA6iFxqx6YL0+pL64PFB+nYZnxL2gYYMU2uqnpKaWJ+6Hv0Q1OXOJ88LA6AtE6rlPZhBoglbk744Q8XK84ewwBt3NCTsZ3sM0sez9iWR8lkwmkiPlYxAosFRfVxQ8YYa0uoT1/GDwOBfsd4x3tsxQRFMV6quKAnaxM02tJOC4OxCw9ul/Gd8SJBumxPKLJCNA9Dbc1d1TVhgltyMMEzpz2lBgJwyV1i2xM/JAgoZd/dLP2JjLB397HnpIZYqO8prXKmX0Y+ba73uan6qpkobIJaV7tuDJznTjcrzrGo2akFmCeEcCSe+rKYSx7Y8buYQzDR4AeL4Te/FbP6CII2QK6MdmYvcTyMKnYL9viU+SkkM76EX1mzQrmviMm9Ze/Z6xWGdzFG39Ns0zMMbw1SyY="
    #OSSRH_PASSWORD
    - secure: "UZ5SRC7sZlkP/rBDzThtcYICpGCeaOzVAC0LzazYd1LgyF29EOiSTLhHjhXOr+E03konKAdKm3nVFld4rl5KJNk/egBlelmDQ6MoLLhGiAujukXPVi1rZ1f/ondpFbzysZub2JM6VkNqJRLKOWQbgZRLcmU2XFJVTQhR0G4O7E917RWF83JAXcTW4US5Dwiv3e90ne83wbA0d3CADrCU9FVi3Qqxv8Pu86x3rZFkcS9tvkhKUb0fJfEUwZaf5zs8o7FURrT7KUJ/cCItECEyBhLlX1C2Dm5s8hyhMsvN11LLPZu5uvqSKLCqY5AAsBxK1C0n5qEbT/ZkAPFQEMGQmqDsxayKqrvQAPJSdDx3tcTyd6zlrDmHuUGQNIDb/oQ0bIYR5qWf+ymRyCHGGhaCvoexJvKqQ9wzJIhlzQwAmWn+rwrwNCytP4C9krFlqpIpPqzXLk9pCIpbMMh302567UAmsfhO5/QQWQhaHnKdZKa6qmmG0QeIEhcAbxPZUOOHWHGjJMaU1O29GFioNgMTRLXAusvpx5bRowyHqtyicDapXACcyeqjr3vSXYq87DTe3rJTRcM6FnIa1eFg8KjyOxZVsdDg/RwXauEKBB1EH5SMmB5shwgegvvP6Khr2r5BLCE1i7CGqEUCOvQ6/Az/fRetkVsz+qNqTpffxL4zWpA="
sudo: false
branches:
  only:
  - master
  - develop
cache:
  directories:
    - $HOME/.gradle
jdk:
  - openjdk8
script:
  - |
    if [ $OSSRH_PASSWORD != "false" ] && cat gradle.properties | grep -q SNAPSHOT; then
      ./gradlew clean build alljavadoc uploadArchives jacocoRootReport copySource coveralls -PnexusUsername="${OSSRH_USERNAME}" -PnexusPassword="${OSSRH_PASSWORD}" -Psigning.keyId="" -Psigning.password=""
    else
      ./gradlew check jacocoRootReport copySource coveralls
    fi
